### ISSUE TITLE
Implement pierone V2 API

### ISSUE THREAD

**Issue by Gregsen** [zalando-stups/pierone-client-java#2]
Soon, there will be pierone V2.

**Comment by hjacobs** [comment]
@Gregsen I haven't checked your Pier One Java client, but the registry v2 will not affect the STUPS API endpoints (e.g. to get the SCM source of a Docker image) --- i.e. probably nothing to do here

**Comment by mrandi** [comment]
@hjacobs I think that this is the line we should change.
https://github.com/zalando-stups/pierone-client-java/blob/master/pierone-client-java-spring/src/main/java/org/zalando/stups/fullstop/clients/pierone/spring/RestTemplatePieroneOperations.java#L47

**Comment by hjacobs** [comment]
OK, I see, yes. you should use our own API endpoint: https://github.com/zalando-stups/pierone/blob/master/resources/api/pierone-api.yaml#L704
